# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d35e7a6b6e8ea2c5084d265259bcc065be4cb4fdccf76bbaca65b6334788a17d852a55888b14d848d2e46f557651e0a0d4738c6715597b52303a7a4de21f99a7

test:
  secret_key_base: b9f79563f1a55cfceb2c9919ddd74a1707a4cb3f81c5d8ff847871e0daf616ab4641a55cf12cf9935b4f20821c03442bf91b3dbca9431dd4d299f5bfa1943b53

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
